export const indianCities = ["Select City",
  "Agartala", "Agra", "Ahmedabad", "Ahmednagar", "Aizawl", "Ajmer", "Akola", "Aligarh", 
  "Allahabad", "Alwar", "Ambala", "Ambarnath", "Ambattur", "Amravati", "Amritsar", "Anand", 
  "Anantapur", "Arrah", "Asansol", "Aurangabad", "Avadi", "Ayodhya", "Baharampur", "Bahraich", 
  "Balasore", "Ballia", "Bally", "Bangalore", "Bankura", "Bareilly", "Bathinda", "Begusarai", 
  "Belgaum", "Bellary", "Berhampore", "Berhampur", "Bettiah", "Bhagalpur", "Bhandara", "Bharatpur", 
  "Bharuch", "Bhavnagar", "Bhilai", "Bhilwara", "Bhimavaram", "Bhiwandi", "Bhiwani", "Bhopal", 
  "Bhubaneswar", "Bhuj", "Bidar", "Bihar Sharif", "Bijapur", "Bikaner", "Bilaspur", "Bokaro Steel City", 
  "Bongaigaon", "Bulandshahr", "Burhanpur", "Chandannagar", "Chandigarh", "Chandrapur", "Chennai", 
  "Chittoor", "Coimbatore", "Cuttack", "Darbhanga", "Davangere", "Dehradun", "Dehri", "Delhi", 
  "Dhanbad", "Dhule", "Dibrugarh", "Dimapur", "Dindigul", "Dispur", "Durg", "Durgapur", "Eluru", 
  "Erode", "Etawah", "Faizabad", "Faridabad", "Farrukhabad", "Fatehpur", "Firozabad", "Gandhinagar", 
  "Gangtok", "Gaya", "Ghaziabad", "Giridih", "Gorakhpur", "Gulbarga", "Guna", "Guntur", "Gurgaon", 
  "Guwahati", "Gwalior", "Hajipur", "Haldia", "Haldwani", "Hamirpur", "Hanumangarh", "Haridwar", 
  "Hassan", "Hathras", "Hazaribagh", "Hindupur", "Hisar", "Hoshiarpur", "Hubli-Dharwad", "Hyderabad", 
  "Ichalkaranji", "Imphal", "Indore", "Jabalpur", "Jagdalpur", "Jaipur", "Jalandhar", "Jalgaon", 
  "Jalna", "Jalpaiguri", "Jammu", "Jamnagar", "Jamshedpur", "Jaunpur", "Jhansi", "Jodhpur", "Junagadh", 
  "Kadapa", "Kakinada", "Kalaburagi", "Kalyan-Dombivli", "Kamarhati", "Kanchipuram", "Kannur", "Kanpur", 
  "Karimnagar", "Kathua", "Katihar", "Kharagpur", "Khora", "Kochi", "Kolhapur", "Kolkata", "Kollam", 
  "Korba", "Kota", "Kottayam", "Kozhikode", "Kulti", "Kurnool", "Latur", "Loni", "Lucknow", "Ludhiana", 
  "Madurai", "Mahbubnagar", "Malappuram", "Malegaon", "Mangalore", "Mango", "Mathura", "Mau", "Meerut", 
  "Mehsana", "Mirzapur", "Moradabad", "Morena", "Motihari", "Mumbai", "Munger", "Muzaffarnagar", 
  "Muzaffarpur", "Mysore", "Nadiad", "Nagercoil", "Nagpur", "Naihati", "Nanded", "Nandurbar", "Nandyal", 
  "Nashik", "Navsari", "Neemuch", "Nellore", "New Delhi", "Nizamabad", "Noida", "North Dumdum", "Ongole", 
  "Orai", "Osmanabad", "Palakkad", "Pali", "Pallavaram", "Panchkula", "Panipat", "Panvel", "Parbhani", 
  "Patiala", "Patna", "Pimpri-Chinchwad", "Pondicherry", "Proddatur", "Pudukkottai", "Pune", "Puri", 
  "Purnia", "Raebareli", "Raichur", "Raiganj", "Raipur", "Rajahmundry", "Rajkot", "Rajnandgaon", 
  "Ramagundam", "Rampur", "Ranchi", "Ratlam", "Rewa", "Rohtak", "Rourkela", "Sagar", "Saharanpur", 
  "Salem", "Sambalpur", "Sambhal", "Sangli", "Satna", "Secunderabad", "Shahjahanpur", "Shimla", 
  "Shimoga", "Shivpuri", "Sikar", "Silchar", "Siliguri", "Singrauli", "Sirsa", "Sitapur", "Siwan", 
  "Solapur", "Sonipat", "South Dumdum", "Sri Ganganagar", "Srikakulam", "Srinagar", "Surat", "Tenali", 
  "Thane", "Thanjavur", "Thiruvananthapuram", "Thoothukudi", "Thrissur", "Tinsukia", "Tirunelveli", 
  "Tirupati", "Tiruppur", "Tiruvannamalai", "Tumkur", "Udaipur", "Udupi", "Ujjain", "Ulhasnagar", 
  "Unnao", "Vadodara", "Varanasi", "Vasai-Virar", "Vellore", "Vijayawada", "Visakhapatnam", "Warangal", 
  "Yamunanagar"
];